apiVersion: apps/v1
kind: Deployment
metadata:
  name: leenustechs-api-service
  namespace: default
  labels:
    app: leenustechs-api-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: leenustechs-api-service
  template:
    metadata:
      labels:
        app: leenustechs-api-service
    spec:
      containers:
        - name: api
          image: hostinger.leenustechs.com.mx:5000/leenustechs-api-service:5be41d0a06fb21bc74f24798fd78e0bb7fc19f8e
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          livenessProbe:
            httpGet:
              path: /api/v1/actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /api/v1/actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
